# Generated by Django 4.0.7 on 2023-06-23 13:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('amenities', models.ManyToManyField(blank=True, to='residence.amenities')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='residence.category')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.city')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.province')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField(default=0)),
                ('base_guests_count', models.PositiveIntegerField(default=1)),
                ('max_guests_count', models.PositiveIntegerField(default=1)),
                ('base_amount', models.PositiveIntegerField()),
                ('adult_extra_amount', models.PositiveIntegerField()),
                ('child_extra_amount', models.PositiveIntegerField()),
                ('baby_extra_amount', models.PositiveIntegerField()),
                ('amenities', models.ManyToManyField(blank=True, to='residence.amenities')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.residence')),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('base_amount', models.PositiveIntegerField()),
                ('adult_extra_amount', models.PositiveIntegerField()),
                ('child_extra_amount', models.PositiveIntegerField()),
                ('baby_extra_amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('empty', 'empty'), ('booked', 'booked')], default='empty', max_length=20)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.calendar')),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.room'),
        ),
        migrations.CreateModel(
            name='Bedroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['title'], name='residence_r_title_1fdfb3_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['residence'], name='residence_r_residen_9a2bbb_idx'),
        ),
        migrations.AddIndex(
            model_name='residence',
            index=models.Index(fields=['title'], name='residence_r_title_877a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='residence',
            index=models.Index(fields=['category'], name='residence_r_categor_6cb6c1_idx'),
        ),
        migrations.AddIndex(
            model_name='residence',
            index=models.Index(fields=['province'], name='residence_r_provinc_cb6b44_idx'),
        ),
        migrations.AddIndex(
            model_name='date',
            index=models.Index(fields=['date'], name='residence_d_date_d1c165_idx'),
        ),
        migrations.AddIndex(
            model_name='date',
            index=models.Index(fields=['calendar'], name='residence_d_calenda_9b6f89_idx'),
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['room'], name='residence_c_room_id_422c68_idx'),
        ),
    ]
