# Generated by Django 4.0.7 on 2023-06-23 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='date',
            name='residence_d_date_d1c165_idx',
        ),
        migrations.RemoveIndex(
            model_name='date',
            name='residence_d_calenda_9b6f89_idx',
        ),
        migrations.RemoveField(
            model_name='residence',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='room',
            name='adult_extra_amount',
        ),
        migrations.RemoveField(
            model_name='room',
            name='baby_extra_amount',
        ),
        migrations.RemoveField(
            model_name='room',
            name='base_amount',
        ),
        migrations.RemoveField(
            model_name='room',
            name='child_extra_amount',
        ),
        migrations.AddField(
            model_name='room',
            name='adult_extra_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='baby_extra_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='child_extra_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residence.room', unique=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_guests_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='date',
            index=models.Index(fields=['date', 'calendar', 'status'], name='residence_d_date_678ede_idx'),
        ),
    ]
