# Generated by Django 4.0.7 on 2023-06-24 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0007_alter_date_adult_extra_amount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='date',
            unique_together={('calendar', 'date')},
        ),
    ]
