# Generated by Django 4.0.7 on 2023-06-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0009_calendar_best_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedroom',
            name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='amenities',
        ),
        migrations.DeleteModel(
            name='Amenities',
        ),
        migrations.DeleteModel(
            name='Bedroom',
        ),
    ]
