# Generated by Django 4.0.7 on 2023-06-24 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0010_remove_bedroom_room_remove_room_amenities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='best_amount',
        ),
    ]
