# Generated by Django 4.0.7 on 2023-06-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residence', '0011_remove_calendar_best_amount'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='residence',
            name='residence_r_categor_6cb6c1_idx',
        ),
        migrations.RemoveField(
            model_name='residence',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
